out1 = predict(mod_1)
out2 = predict(mod_2)
out3 = predict(mod_3)
out4 = predict(mod_4)
out5 = predict(mod_5)
out6 = predict(mod_6)
out7 = predict(mod_7)
out8 = predict(mod_8)
out9 = predict(mod_9)
out10 = predict(mod_10)
out11 = predict(mod_11)
out12 = predict(mod_12)
out13 = predict(mod_13)
out14 = predict(mod_14)
out15 = predict(mod_15)
out16 = predict(mod_16)
out17 = predict(mod_17)
out18 = predict(mod_18)
out19 = predict(mod_19)
out20 = predict(mod_20)
out21 = predict(mod_21)
out22 = predict(mod_22)
out23 = predict(mod_23)
out24 = predict(mod_24)
out25 = predict(mod_25)
out26 = predict(mod_26)
out27 = predict(mod_27)
out28 = predict(mod_28)
out29 = predict(mod_29)
out30 = predict(mod_30)
out31 = predict(mod_31)
out32 = predict(mod_32)
out33 = predict(mod_33)
out34 = predict(mod_34)
out35 = predict(mod_35)
out36 = predict(mod_36)
out37 = predict(mod_37)
out38 = predict(mod_38)
out39 = predict(mod_39)
out40 = predict(mod_40)
out41 = predict(mod_41)
out42 = predict(mod_42)
out43 = predict(mod_43)
out44 = predict(mod_44)
out45 = predict(mod_45)
out46 = predict(mod_46)
out47 = predict(mod_47)
out48 = predict(mod_48)
out49 = predict(mod_49)
out50 = predict(mod_50)
out51 = predict(mod_51)
out52 = predict(mod_52)
out53 = predict(mod_53)
out54 = predict(mod_54)
out55 = predict(mod_55)
out56 = predict(mod_56)
out57 = predict(mod_57)
out58 = predict(mod_58)
out59 = predict(mod_59)
out60 = predict(mod_60)
out61 = predict(mod_61)
out62 = predict(mod_62)
out63 = predict(mod_63)
out64 = predict(mod_64)
out65 = predict(mod_65)
out66 = predict(mod_66)
out67 = predict(mod_67)
out68 = predict(mod_68)
out69 = predict(mod_69)
out70 = predict(mod_70)
out71 = predict(mod_71)
out72 = predict(mod_72)
out73 = predict(mod_73)
out74 = predict(mod_74)
out75 = predict(mod_75)
out76 = predict(mod_76)
out77 = predict(mod_77)
out78 = predict(mod_78)
out79 = predict(mod_79)
out80 = predict(mod_80)
out81 = predict(mod_81)
out82 = predict(mod_82)
out83 = predict(mod_83)
out84 = predict(mod_84)
out85 = predict(mod_85)
out86 = predict(mod_86)
out87 = predict(mod_87)
out88 = predict(mod_88)
out89 = predict(mod_89)
out90 = predict(mod_90)
out91 = predict(mod_91)
out92 = predict(mod_92)
out93 = predict(mod_93)
out94 = predict(mod_94)
out95 = predict(mod_95)
out96 = predict(mod_96)
out97 = predict(mod_97)
out98 = predict(mod_98)
out99 = predict(mod_99)

pred.response1 <- colnames(out1)[max.col(out1, ties.method = c("random"))]
pred.response2 <- colnames(out2)[max.col(out2, ties.method = c("random"))]
pred.response3 <- colnames(out3)[max.col(out3, ties.method = c("random"))]
pred.response4 <- colnames(out4)[max.col(out4, ties.method = c("random"))]
pred.response5 <- colnames(out5)[max.col(out5, ties.method = c("random"))]
pred.response6 <- colnames(out6)[max.col(out6, ties.method = c("random"))]
pred.response7 <- colnames(out7)[max.col(out7, ties.method = c("random"))]
pred.response8 <- colnames(out8)[max.col(out8, ties.method = c("random"))]
pred.response9 <- colnames(out9)[max.col(out9, ties.method = c("random"))]
pred.response10 <- colnames(out10)[max.col(out10, ties.method = c("random"))]
pred.response11 <- colnames(out11)[max.col(out11, ties.method = c("random"))]
pred.response12 <- colnames(out12)[max.col(out12, ties.method = c("random"))]
pred.response13 <- colnames(out13)[max.col(out13, ties.method = c("random"))]
pred.response14 <- colnames(out14)[max.col(out14, ties.method = c("random"))]
pred.response15 <- colnames(out15)[max.col(out15, ties.method = c("random"))]
pred.response16 <- colnames(out16)[max.col(out16, ties.method = c("random"))]
pred.response17 <- colnames(out17)[max.col(out17, ties.method = c("random"))]
pred.response18 <- colnames(out18)[max.col(out18, ties.method = c("random"))]
pred.response19 <- colnames(out19)[max.col(out19, ties.method = c("random"))]
pred.response20 <- colnames(out20)[max.col(out20, ties.method = c("random"))]
pred.response21 <- colnames(out21)[max.col(out21, ties.method = c("random"))]
pred.response22 <- colnames(out22)[max.col(out22, ties.method = c("random"))]
pred.response23 <- colnames(out23)[max.col(out23, ties.method = c("random"))]
pred.response24 <- colnames(out24)[max.col(out24, ties.method = c("random"))]
pred.response25 <- colnames(out25)[max.col(out25, ties.method = c("random"))]
pred.response26 <- colnames(out26)[max.col(out26, ties.method = c("random"))]
pred.response27 <- colnames(out27)[max.col(out27, ties.method = c("random"))]
pred.response28 <- colnames(out28)[max.col(out28, ties.method = c("random"))]
pred.response29 <- colnames(out29)[max.col(out29, ties.method = c("random"))]
pred.response30 <- colnames(out30)[max.col(out30, ties.method = c("random"))]
pred.response31 <- colnames(out31)[max.col(out31, ties.method = c("random"))]
pred.response32 <- colnames(out32)[max.col(out32, ties.method = c("random"))]
pred.response33 <- colnames(out33)[max.col(out33, ties.method = c("random"))]
pred.response34 <- colnames(out34)[max.col(out34, ties.method = c("random"))]
pred.response35 <- colnames(out35)[max.col(out35, ties.method = c("random"))]
pred.response36 <- colnames(out36)[max.col(out36, ties.method = c("random"))]
pred.response37 <- colnames(out37)[max.col(out37, ties.method = c("random"))]
pred.response38 <- colnames(out38)[max.col(out38, ties.method = c("random"))]
pred.response39 <- colnames(out39)[max.col(out39, ties.method = c("random"))]
pred.response40 <- colnames(out40)[max.col(out40, ties.method = c("random"))]
pred.response41 <- colnames(out41)[max.col(out41, ties.method = c("random"))]
pred.response42 <- colnames(out42)[max.col(out42, ties.method = c("random"))]
pred.response43 <- colnames(out43)[max.col(out43, ties.method = c("random"))]
pred.response44 <- colnames(out44)[max.col(out44, ties.method = c("random"))]
pred.response45 <- colnames(out45)[max.col(out45, ties.method = c("random"))]
pred.response46 <- colnames(out46)[max.col(out46, ties.method = c("random"))]
pred.response47 <- colnames(out47)[max.col(out47, ties.method = c("random"))]
pred.response48 <- colnames(out48)[max.col(out48, ties.method = c("random"))]
pred.response49 <- colnames(out49)[max.col(out49, ties.method = c("random"))]
pred.response50 <- colnames(out50)[max.col(out50, ties.method = c("random"))]
pred.response51 <- colnames(out51)[max.col(out51, ties.method = c("random"))]
pred.response52 <- colnames(out52)[max.col(out52, ties.method = c("random"))]
pred.response53 <- colnames(out53)[max.col(out53, ties.method = c("random"))]
pred.response54 <- colnames(out54)[max.col(out54, ties.method = c("random"))]
pred.response55 <- colnames(out55)[max.col(out55, ties.method = c("random"))]
pred.response56 <- colnames(out56)[max.col(out56, ties.method = c("random"))]
pred.response57 <- colnames(out57)[max.col(out57, ties.method = c("random"))]
pred.response58 <- colnames(out58)[max.col(out58, ties.method = c("random"))]
pred.response59 <- colnames(out59)[max.col(out59, ties.method = c("random"))]
pred.response60 <- colnames(out60)[max.col(out60, ties.method = c("random"))]
pred.response61 <- colnames(out61)[max.col(out61, ties.method = c("random"))]
pred.response62 <- colnames(out62)[max.col(out62, ties.method = c("random"))]
pred.response63 <- colnames(out63)[max.col(out63, ties.method = c("random"))]
pred.response64 <- colnames(out64)[max.col(out64, ties.method = c("random"))]
pred.response65 <- colnames(out65)[max.col(out65, ties.method = c("random"))]
pred.response66 <- colnames(out66)[max.col(out66, ties.method = c("random"))]
pred.response67 <- colnames(out67)[max.col(out67, ties.method = c("random"))]
pred.response68 <- colnames(out68)[max.col(out68, ties.method = c("random"))]
pred.response69 <- colnames(out69)[max.col(out69, ties.method = c("random"))]
pred.response70 <- colnames(out70)[max.col(out70, ties.method = c("random"))]
pred.response71 <- colnames(out71)[max.col(out71, ties.method = c("random"))]
pred.response72 <- colnames(out72)[max.col(out72, ties.method = c("random"))]
pred.response73 <- colnames(out73)[max.col(out73, ties.method = c("random"))]
pred.response74 <- colnames(out74)[max.col(out74, ties.method = c("random"))]
pred.response75 <- colnames(out75)[max.col(out75, ties.method = c("random"))]
pred.response76 <- colnames(out76)[max.col(out76, ties.method = c("random"))]
pred.response77 <- colnames(out77)[max.col(out77, ties.method = c("random"))]
pred.response78 <- colnames(out78)[max.col(out78, ties.method = c("random"))]
pred.response79 <- colnames(out79)[max.col(out79, ties.method = c("random"))]
pred.response80 <- colnames(out80)[max.col(out80, ties.method = c("random"))]
pred.response81 <- colnames(out81)[max.col(out81, ties.method = c("random"))]
pred.response82 <- colnames(out82)[max.col(out82, ties.method = c("random"))]
pred.response83 <- colnames(out83)[max.col(out83, ties.method = c("random"))]
pred.response84 <- colnames(out84)[max.col(out84, ties.method = c("random"))]
pred.response85 <- colnames(out85)[max.col(out85, ties.method = c("random"))]
pred.response86 <- colnames(out86)[max.col(out86, ties.method = c("random"))]
pred.response87 <- colnames(out87)[max.col(out87, ties.method = c("random"))]
pred.response88 <- colnames(out88)[max.col(out88, ties.method = c("random"))]
pred.response89 <- colnames(out89)[max.col(out89, ties.method = c("random"))]
pred.response90 <- colnames(out90)[max.col(out90, ties.method = c("random"))]
pred.response91 <- colnames(out91)[max.col(out91, ties.method = c("random"))]
pred.response92 <- colnames(out92)[max.col(out92, ties.method = c("random"))]
pred.response93 <- colnames(out93)[max.col(out93, ties.method = c("random"))]
pred.response94 <- colnames(out94)[max.col(out94, ties.method = c("random"))]
pred.response95 <- colnames(out95)[max.col(out95, ties.method = c("random"))]
pred.response96 <- colnames(out96)[max.col(out96, ties.method = c("random"))]
pred.response97 <- colnames(out97)[max.col(out97, ties.method = c("random"))]
pred.response98 <- colnames(out98)[max.col(out98, ties.method = c("random"))]
pred.response99 <- colnames(out99)[max.col(out99, ties.method = c("random"))]

TestOut1 = predict(mod_1, test3)
TestOut2 = predict(mod_2, test3)
TestOut3 = predict(mod_3, test3)
TestOut4 = predict(mod_4, test3)
TestOut5 = predict(mod_5, test3)
TestOut6 = predict(mod_6, test3)
TestOut7 = predict(mod_7, test3)
TestOut8 = predict(mod_8, test3)
TestOut9 = predict(mod_9, test3)
TestOut10 = predict(mod_10, test3)
TestOut11 = predict(mod_11, test3)
TestOut12 = predict(mod_12, test3)
TestOut13 = predict(mod_13, test3)
TestOut14 = predict(mod_14, test3)
TestOut15 = predict(mod_15, test3)
TestOut16 = predict(mod_16, test3)
TestOut17 = predict(mod_17, test3)
TestOut18 = predict(mod_18, test3)
TestOut19 = predict(mod_19, test3)
TestOut20 = predict(mod_20, test3)
TestOut21 = predict(mod_21, test3)
TestOut22 = predict(mod_22, test3)
TestOut23 = predict(mod_23, test3)
TestOut24 = predict(mod_24, test3)
TestOut25 = predict(mod_25, test3)
TestOut26 = predict(mod_26, test3)
TestOut27 = predict(mod_27, test3)
TestOut28 = predict(mod_28, test3)
TestOut29 = predict(mod_29, test3)
TestOut30 = predict(mod_30, test3)
TestOut31 = predict(mod_31, test3)
TestOut32 = predict(mod_32, test3)
TestOut33 = predict(mod_33, test3)
TestOut34 = predict(mod_34, test3)
TestOut35 = predict(mod_35, test3)
TestOut36 = predict(mod_36, test3)
TestOut37 = predict(mod_37, test3)
TestOut38 = predict(mod_38, test3)
TestOut39 = predict(mod_39, test3)
TestOut40 = predict(mod_40, test3)
TestOut41 = predict(mod_41, test3)
TestOut42 = predict(mod_42, test3)
TestOut43 = predict(mod_43, test3)
TestOut44 = predict(mod_44, test3)
TestOut45 = predict(mod_45, test3)
TestOut46 = predict(mod_46, test3)
TestOut47 = predict(mod_47, test3)
TestOut48 = predict(mod_48, test3)
TestOut49 = predict(mod_49, test3)
TestOut50 = predict(mod_50, test3)
TestOut51 = predict(mod_51, test3)
TestOut52 = predict(mod_52, test3)
TestOut53 = predict(mod_53, test3)
TestOut54 = predict(mod_54, test3)
TestOut55 = predict(mod_55, test3)
TestOut56 = predict(mod_56, test3)
TestOut57 = predict(mod_57, test3)
TestOut58 = predict(mod_58, test3)
TestOut59 = predict(mod_59, test3)
TestOut60 = predict(mod_60, test3)
TestOut61 = predict(mod_61, test3)
TestOut62 = predict(mod_62, test3)
TestOut63 = predict(mod_63, test3)
TestOut64 = predict(mod_64, test3)
TestOut65 = predict(mod_65, test3)
TestOut66 = predict(mod_66, test3)
TestOut67 = predict(mod_67, test3)
TestOut68 = predict(mod_68, test3)
TestOut69 = predict(mod_69, test3)
TestOut70 = predict(mod_70, test3)
TestOut71 = predict(mod_71, test3)
TestOut72 = predict(mod_72, test3)
TestOut73 = predict(mod_73, test3)
TestOut74 = predict(mod_74, test3)
TestOut75 = predict(mod_75, test3)
TestOut76 = predict(mod_76, test3)
TestOut77 = predict(mod_77, test3)
TestOut78 = predict(mod_78, test3)
TestOut79 = predict(mod_79, test3)
TestOut80 = predict(mod_80, test3)
TestOut81 = predict(mod_81, test3)
TestOut82 = predict(mod_82, test3)
TestOut83 = predict(mod_83, test3)
TestOut84 = predict(mod_84, test3)
TestOut85 = predict(mod_85, test3)
TestOut86 = predict(mod_86, test3)
TestOut87 = predict(mod_87, test3)
TestOut88 = predict(mod_88, test3)
TestOut89 = predict(mod_89, test3)
TestOut90 = predict(mod_90, test3)
TestOut91 = predict(mod_91, test3)
TestOut92 = predict(mod_92, test3)
TestOut93 = predict(mod_93, test3)
TestOut94 = predict(mod_94, test3)
TestOut95 = predict(mod_95, test3)
TestOut96 = predict(mod_96, test3)
TestOut97 = predict(mod_97, test3)
TestOut98 = predict(mod_98, test3)
TestOut99 = predict(mod_99, test3)

TestPred.response1 <- colnames(TestOut1)[max.col(TestOut1, ties.method = c("random"))]
TestPred.response2 <- colnames(TestOut2)[max.col(TestOut2, ties.method = c("random"))]
TestPred.response3 <- colnames(TestOut3)[max.col(TestOut3, ties.method = c("random"))]
TestPred.response4 <- colnames(TestOut4)[max.col(TestOut4, ties.method = c("random"))]
TestPred.response5 <- colnames(TestOut5)[max.col(TestOut5, ties.method = c("random"))]
TestPred.response6 <- colnames(TestOut6)[max.col(TestOut6, ties.method = c("random"))]
TestPred.response7 <- colnames(TestOut7)[max.col(TestOut7, ties.method = c("random"))]
TestPred.response8 <- colnames(TestOut8)[max.col(TestOut8, ties.method = c("random"))]
TestPred.response9 <- colnames(TestOut9)[max.col(TestOut9, ties.method = c("random"))]
TestPred.response10 <- colnames(TestOut10)[max.col(TestOut10, ties.method = c("random"))]
TestPred.response11 <- colnames(TestOut11)[max.col(TestOut11, ties.method = c("random"))]
TestPred.response12 <- colnames(TestOut12)[max.col(TestOut12, ties.method = c("random"))]
TestPred.response13 <- colnames(TestOut13)[max.col(TestOut13, ties.method = c("random"))]
TestPred.response14 <- colnames(TestOut14)[max.col(TestOut14, ties.method = c("random"))]
TestPred.response15 <- colnames(TestOut15)[max.col(TestOut15, ties.method = c("random"))]
TestPred.response16 <- colnames(TestOut16)[max.col(TestOut16, ties.method = c("random"))]
TestPred.response17 <- colnames(TestOut17)[max.col(TestOut17, ties.method = c("random"))]
TestPred.response18 <- colnames(TestOut18)[max.col(TestOut18, ties.method = c("random"))]
TestPred.response19 <- colnames(TestOut19)[max.col(TestOut19, ties.method = c("random"))]
TestPred.response20 <- colnames(TestOut20)[max.col(TestOut20, ties.method = c("random"))]
TestPred.response21 <- colnames(TestOut21)[max.col(TestOut21, ties.method = c("random"))]
TestPred.response22 <- colnames(TestOut22)[max.col(TestOut22, ties.method = c("random"))]
TestPred.response23 <- colnames(TestOut23)[max.col(TestOut23, ties.method = c("random"))]
TestPred.response24 <- colnames(TestOut24)[max.col(TestOut24, ties.method = c("random"))]
TestPred.response25 <- colnames(TestOut25)[max.col(TestOut25, ties.method = c("random"))]
TestPred.response26 <- colnames(TestOut26)[max.col(TestOut26, ties.method = c("random"))]
TestPred.response27 <- colnames(TestOut27)[max.col(TestOut27, ties.method = c("random"))]
TestPred.response28 <- colnames(TestOut28)[max.col(TestOut28, ties.method = c("random"))]
TestPred.response29 <- colnames(TestOut29)[max.col(TestOut29, ties.method = c("random"))]
TestPred.response30 <- colnames(TestOut30)[max.col(TestOut30, ties.method = c("random"))]
TestPred.response31 <- colnames(TestOut31)[max.col(TestOut31, ties.method = c("random"))]
TestPred.response32 <- colnames(TestOut32)[max.col(TestOut32, ties.method = c("random"))]
TestPred.response33 <- colnames(TestOut33)[max.col(TestOut33, ties.method = c("random"))]
TestPred.response34 <- colnames(TestOut34)[max.col(TestOut34, ties.method = c("random"))]
TestPred.response35 <- colnames(TestOut35)[max.col(TestOut35, ties.method = c("random"))]
TestPred.response36 <- colnames(TestOut36)[max.col(TestOut36, ties.method = c("random"))]
TestPred.response37 <- colnames(TestOut37)[max.col(TestOut37, ties.method = c("random"))]
TestPred.response38 <- colnames(TestOut38)[max.col(TestOut38, ties.method = c("random"))]
TestPred.response39 <- colnames(TestOut39)[max.col(TestOut39, ties.method = c("random"))]
TestPred.response40 <- colnames(TestOut40)[max.col(TestOut40, ties.method = c("random"))]
TestPred.response41 <- colnames(TestOut41)[max.col(TestOut41, ties.method = c("random"))]
TestPred.response42 <- colnames(TestOut42)[max.col(TestOut42, ties.method = c("random"))]
TestPred.response43 <- colnames(TestOut43)[max.col(TestOut43, ties.method = c("random"))]
TestPred.response44 <- colnames(TestOut44)[max.col(TestOut44, ties.method = c("random"))]
TestPred.response45 <- colnames(TestOut45)[max.col(TestOut45, ties.method = c("random"))]
TestPred.response46 <- colnames(TestOut46)[max.col(TestOut46, ties.method = c("random"))]
TestPred.response47 <- colnames(TestOut47)[max.col(TestOut47, ties.method = c("random"))]
TestPred.response48 <- colnames(TestOut48)[max.col(TestOut48, ties.method = c("random"))]
TestPred.response49 <- colnames(TestOut49)[max.col(TestOut49, ties.method = c("random"))]
TestPred.response50 <- colnames(TestOut50)[max.col(TestOut50, ties.method = c("random"))]
TestPred.response51 <- colnames(TestOut51)[max.col(TestOut51, ties.method = c("random"))]
TestPred.response52 <- colnames(TestOut52)[max.col(TestOut52, ties.method = c("random"))]
TestPred.response53 <- colnames(TestOut53)[max.col(TestOut53, ties.method = c("random"))]
TestPred.response54 <- colnames(TestOut54)[max.col(TestOut54, ties.method = c("random"))]
TestPred.response55 <- colnames(TestOut55)[max.col(TestOut55, ties.method = c("random"))]
TestPred.response56 <- colnames(TestOut56)[max.col(TestOut56, ties.method = c("random"))]
TestPred.response57 <- colnames(TestOut57)[max.col(TestOut57, ties.method = c("random"))]
TestPred.response58 <- colnames(TestOut58)[max.col(TestOut58, ties.method = c("random"))]
TestPred.response59 <- colnames(TestOut59)[max.col(TestOut59, ties.method = c("random"))]
TestPred.response60 <- colnames(TestOut60)[max.col(TestOut60, ties.method = c("random"))]
TestPred.response61 <- colnames(TestOut61)[max.col(TestOut61, ties.method = c("random"))]
TestPred.response62 <- colnames(TestOut62)[max.col(TestOut62, ties.method = c("random"))]
TestPred.response63 <- colnames(TestOut63)[max.col(TestOut63, ties.method = c("random"))]
TestPred.response64 <- colnames(TestOut64)[max.col(TestOut64, ties.method = c("random"))]
TestPred.response65 <- colnames(TestOut65)[max.col(TestOut65, ties.method = c("random"))]
TestPred.response66 <- colnames(TestOut66)[max.col(TestOut66, ties.method = c("random"))]
TestPred.response67 <- colnames(TestOut67)[max.col(TestOut67, ties.method = c("random"))]
TestPred.response68 <- colnames(TestOut68)[max.col(TestOut68, ties.method = c("random"))]
TestPred.response69 <- colnames(TestOut69)[max.col(TestOut69, ties.method = c("random"))]
TestPred.response70 <- colnames(TestOut70)[max.col(TestOut70, ties.method = c("random"))]
TestPred.response71 <- colnames(TestOut71)[max.col(TestOut71, ties.method = c("random"))]
TestPred.response72 <- colnames(TestOut72)[max.col(TestOut72, ties.method = c("random"))]
TestPred.response73 <- colnames(TestOut73)[max.col(TestOut73, ties.method = c("random"))]
TestPred.response74 <- colnames(TestOut74)[max.col(TestOut74, ties.method = c("random"))]
TestPred.response75 <- colnames(TestOut75)[max.col(TestOut75, ties.method = c("random"))]
TestPred.response76 <- colnames(TestOut76)[max.col(TestOut76, ties.method = c("random"))]
TestPred.response77 <- colnames(TestOut77)[max.col(TestOut77, ties.method = c("random"))]
TestPred.response78 <- colnames(TestOut78)[max.col(TestOut78, ties.method = c("random"))]
TestPred.response79 <- colnames(TestOut79)[max.col(TestOut79, ties.method = c("random"))]
TestPred.response80 <- colnames(TestOut80)[max.col(TestOut80, ties.method = c("random"))]
TestPred.response81 <- colnames(TestOut81)[max.col(TestOut81, ties.method = c("random"))]
TestPred.response82 <- colnames(TestOut82)[max.col(TestOut82, ties.method = c("random"))]
TestPred.response83 <- colnames(TestOut83)[max.col(TestOut83, ties.method = c("random"))]
TestPred.response84 <- colnames(TestOut84)[max.col(TestOut84, ties.method = c("random"))]
TestPred.response85 <- colnames(TestOut85)[max.col(TestOut85, ties.method = c("random"))]
TestPred.response86 <- colnames(TestOut86)[max.col(TestOut86, ties.method = c("random"))]
TestPred.response87 <- colnames(TestOut87)[max.col(TestOut87, ties.method = c("random"))]
TestPred.response88 <- colnames(TestOut88)[max.col(TestOut88, ties.method = c("random"))]
TestPred.response89 <- colnames(TestOut89)[max.col(TestOut89, ties.method = c("random"))]
TestPred.response90 <- colnames(TestOut90)[max.col(TestOut90, ties.method = c("random"))]
TestPred.response91 <- colnames(TestOut91)[max.col(TestOut91, ties.method = c("random"))]
TestPred.response92 <- colnames(TestOut92)[max.col(TestOut92, ties.method = c("random"))]
TestPred.response93 <- colnames(TestOut93)[max.col(TestOut93, ties.method = c("random"))]
TestPred.response94 <- colnames(TestOut94)[max.col(TestOut94, ties.method = c("random"))]
TestPred.response95 <- colnames(TestOut95)[max.col(TestOut95, ties.method = c("random"))]
TestPred.response96 <- colnames(TestOut96)[max.col(TestOut96, ties.method = c("random"))]
TestPred.response97 <- colnames(TestOut97)[max.col(TestOut97, ties.method = c("random"))]
TestPred.response98 <- colnames(TestOut98)[max.col(TestOut98, ties.method = c("random"))]
TestPred.response99 <- colnames(TestOut99)[max.col(TestOut99, ties.method = c("random"))]

for (i in 1:99) {
     temp = 1 - mean(train3$click != eval(parse(paste0("pred.response", i)))) 
     Accuracies[[i]] = temp
}
